In [79]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [80]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\reddy\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\reddy\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\reddy\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [81]:
import os

print(os.path.exists("insurance.xlsx"))

True

In [82]:
print(os.getcwd())

C:\Users\reddy\vamshi-projects

In [83]:
import pandas as pd

df = pd.read_csv("insurance.xlsx", sep="\t")
print(df.head())

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [84]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [86]:
df.shape

(1338, 7)

In [143]:
df.corr()

               age       sex       bmi  children    smoker  expenses
age       1.000000 -0.020856  0.109341  0.042469 -0.025019  0.299008
sex      -0.020856  1.000000  0.046380  0.017163  0.076185  0.057292
bmi       0.109341  0.046380  1.000000  0.012645  0.003968  0.198576
children  0.042469  0.017163  0.012645  1.000000  0.007673  0.067998
smoker   -0.025019  0.076185  0.003968  0.007673  1.000000  0.787251
expenses  0.299008  0.057292  0.198576  0.067998  0.787251  1.000000

In [88]:
categories = []
continuous =[]
check = []
d_types = dict(df.dtypes)
d_types

from pandas.api.types import (
    is_string_dtype,
    is_float_dtype,
    is_integer_dtype,
)

for col in df.columns:
    if is_string_dtype(df[col]):
        categories.append(col)
    elif is_float_dtype(df[col]):
        continuous.append(col)
    elif is_integer_dtype(df[col]):
        check.append(col)

print(categories,continuous,check)

['sex', 'smoker', 'region'] ['bmi', 'expenses'] ['age', 'children']

In [89]:
for col in df.columns:
    if is_string_dtype(df[col]):
        print(f"<==============={col}=============>")
        print(df[col].value_counts())

<===============sex=============>
sex
male      676
female    662
Name: count, dtype: int64
<===============smoker=============>
smoker
no     1064
yes     274
Name: count, dtype: int64
<===============region=============>
region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [90]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [91]:
df.corr(numeric_only=True)

               age       bmi  children  expenses
age       1.000000  0.109341  0.042469  0.299008
bmi       0.109341  1.000000  0.012645  0.198576
children  0.042469  0.012645  1.000000  0.067998
expenses  0.299008  0.198576  0.067998  1.000000

In [92]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [93]:
df.drop('region',axis=1,inplace=True)

In [94]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
expenses    0
dtype: int64

In [103]:
df['sex'] = df['sex'].replace({'female':0, 'male':1})

In [104]:
df['smoker']=df['smoker'].replace({'no':0,'yes':1})

In [105]:
X = df.drop('expenses',axis=1)
y = df['expenses']

In [106]:
print(df['sex'].unique())
print(df['smoker'].unique())

[0 1]
[1 0]

In [127]:
X_train

      age sex   bmi  children smoker
333    56   0  28.8         0      0
644    43   1  35.3         2      0
1134   28   1  33.8         0      0
852    46   0  35.5         0      1
514    39   1  28.3         1      1
...   ...  ..   ...       ...    ...
56     58   0  31.8         2      0
501    43   1  26.0         0      0
638    39   1  26.4         0      1
348    36   0  29.9         1      0
382    55   1  33.0         0      0

[1070 rows x 5 columns]

In [161]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [162]:
from sklearn.linear_model import ElasticNet
enr_base = ElasticNet()
enr_base.fit(X_train,y_train)

train_predictions = enr_base.predict(X_train)
test_predictions = enr_base.predict(X_test)

print("Train R2" ,enr_base.score(X_train,y_train))
print("Test R2:" ,enr_base.score(X_test,y_test))
from sklearn.model_selection import cross_val_score
print("Cross Validation score:",cross_val_score(enr_base,X,y,cv=5).mean())

Train R2 0.3824976446106315
Test R2: 0.4178740802692563
Cross Validation score: 0.3889250431216654

In [163]:
from sklearn.model_selection import GridSearchCV
estimator = ElasticNet()
param_grid = {"alpha":[0.1,0.2,1,2,3,5,10],"l1_ratio":[0.1,0.5,0.75,0.9,0.95,1]}
model_hp = GridSearchCV(estimator,param_grid,cv=5,scoring='neg_mean_squared_error')
model_hp.fit(X_train,y_train)
model_hp.best_params_

{'alpha': 10, 'l1_ratio': 1}

In [164]:
enr_best = ElasticNet(alpha=10,l1_ratio=1)
enr_best.fit(X_train,y_train)
print("Intercept:",enr_best.intercept_)
print("coeffiecents:",enr_best.coef_)

train_predictions = enr_best.predict(X_train)
test_predictions = enr_best.predict(X_test)

print("Train R2:", enr_best.score(X_train, y_train))
print("Test R2:", enr_best.score(X_test, y_test))
print("Cross Validation Score",cross_val_score(enr_best,X,y,cv=5).mean())

Intercept: -12090.596482929921
coeffiecents: [  256.95837352    -0.           327.41949089   421.13830688
 23591.20907287]
Train R2: 0.7411094487260131
Test R2: 0.7809614490519589
Cross Validation Score 0.7467299170217538

In [148]:
input_data = { "age":31,
               "sex":'female',
               "bmi":25.74,  
               "children":0,
               "smoker":'no',
               "region":"northeast"
}

In [142]:
df_test = pd.DataFrame(input_data, index=[0])

# Remove region because your model was trained without it
df_test = df_test.drop("region", axis=1)

# Convert categorical values to numeric
df_test["sex"] = df_test["sex"].replace({"female": 0, "male": 1})
df_test["smoker"] = df_test["smoker"].replace({"no": 0, "yes": 1})

prediction = enr_best.predict(df_test)

print(prediction)

[4359.82451623]